### ISSUE TITLE
Request for access to bitzilla account

### ISSUE THREAD

**Issue by vinithvini** [MozillaTN/bitzilla#1]
Hello bro,
I need to build the club website for Bannari amman campus, so can you give me the access to the Repository...

**Comment by iamVP7** [comment]
@hellokarthic  please use this repo.. please help him to finish

**Comment by prasanthp96** [comment]
@vinithvini I think the access is already granted and an invitation has been sent long back, you need to accept the invitation to start working. check your github notifications and there you will find the invitation.

**Comment by iamVP7** [comment]
https://github.com/MozillaTN/bitzilla/invitations
